micronaut:
  application:
    name: micUserServiceJpa
datasources:
  default:
    url: jdbc:mysql://localhost:3306/mnm
    username: root
    password: test
    schema-generate: CREATE_DROP
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
jpa.default.properties.hibernate.hbm2ddl.auto: update
show_sql: true
netty:
  default:
    allocator:
      max-order: 3
