micronaut:
  application:
    name: configurationInjectionMn
  server:
    port: 8081
hello:
  world:
    message: "Hello from application.yml"
    translation:
      de: "Hello Walt"
      en: "Hello World"
netty:
  default:
    allocator:
      max-order: 3
