micronaut:
  application:
    name: micronautDb
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false

    datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
    user: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:test}

datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
    schema-genenerate: NONE
    dialect: POSTGRES

# micronaut-data-jpa
jpa:
  default:
    packages-to-scan:
      - "com.wasim.persistence"
    properties:
      hibernate:
        show_sql: false
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: none
